apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment-2
  labels:
    app: helloworld-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld-3
  template:
    metadata:
      labels:
        app: helloworld-3
    spec:
      containers:
      - name: k8s-demo
        image: amitvashist7/k8s-tiny-web
        ports:
        - name: nodejs-port
          containerPort: 80
      nodeSelector:
        matchExpressions:
        - key: env
          operator: In
          values: prod
